import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: uuid(),
    title: "The Mizoquii",
    author: "Caleb Durden",
    price: "$7.99",
    productImage: require("../../assets/fiction00.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    title: "A Trace of Poison",
    author: "Colleen Cambridge",
    price: "$22.10",
    productImage: require("../../assets/fiction01.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "fiction",
  },{
    _id: uuid(),
    title: "Apoca Lips",
    author: "Piers Anthony",
    price: "$16.99",
    productImage: require("../../assets/fiction02.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "fiction",
  },{
    _id: uuid(),
    title: "Imaginary Friends",
    author: "Arlene F. Marks",
    price: "$4.99",
    productImage: require("../../assets/fiction03.jpg"),
    inStock: false,
    rating: "4",
    isFastDelivery: false,
    categoryName: "fiction",
  },{
    _id: uuid(),
    title: "After the Revolution",
    author: "Robert Evans",
    price: "$18.99",
    productImage: require("../../assets/fiction04.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: true,
    categoryName: "fiction",
  },{
    _id: uuid(),
    title: "The Measure of a Man",
    author: "William W. Johnstone",
    price: "$9.49",
    productImage: require("../../assets/fiction05.jpg"),
    inStock: false,
    rating: "4",
    isFastDelivery: false,
    categoryName: "fiction",
  },{
    _id: uuid(),
    title: "The End of the Cities",
    author: "Laurel Solorzano",
    price: "$4.99",
    productImage: require("../../assets/fiction22.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "fiction",
  },{
    _id: uuid(),
    title: "The Lost City of Book",
    author: "Gregory L Norris",
    price: "$9.99",
    productImage: require("../../assets/fiction.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "fiction",
  },{
    _id: uuid(),
    title: "Outfoxed",
    author: "Melinda Metz",
    price: "$11.01",
    productImage: require("../../assets/fiction23.jpg"),
    inStock: false,
    rating: "4",
    isFastDelivery: false,
    categoryName: "fiction",
  },{
    _id: uuid(),
    title: "Steeped in Secrets",
    author: "Lauren Elliott",
    price: "$22.10",
    productImage: require("../../assets/fiction24.jpg"),
    inStock: false,
    rating: "3",
    isFastDelivery: false,
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    title: "A Ghost in Shining Armor",
    author: "Therese Beharrie",
    price: "$14.41",
    productImage: require("../../assets/fiction25.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: true,
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    title: "Along the Shore",
    author: "Rochelle Alers",
    price: "$14.41",
    productImage: require("../../assets/fiction26.jpg"),
    inStock: false,
    rating: "3",
    isFastDelivery: false,
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    title: "The Wife Before",
    author: "Shanora Williams",
    price: "$14.41",
    productImage: require("../../assets/fiction27.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    title: "Magician of Light",
    author: "J Fremont",
    price: "$9.95",
    productImage: require("../../assets/fiction28.jpg"),
    inStock: false,
    rating: "4",
    isFastDelivery: false,
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    title: "Gone but Still Here",
    author: "Jennifer Dance",
    price: "$9.99",
    productImage: require("../../assets/fiction29.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: true,
    categoryName: "fiction",
  },
  {
    _id: uuid(),
    title: "Black Mouth",
    author: "Ronald Malfi",
    price: "$10.49",
    productImage: require("../../assets/horror00.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "horror",
  },
  {
    _id: uuid(),
    title: "The Pallbearers’ Club",
    author: "Paul Tremblay",
    price: "$10.49",
    productImage: require("../../assets/horror01.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "horror",
  },{
    _id: uuid(),
    title: "The Queen of Bedlam",
    author: "Robert McCammon",
    price: "$17.99",
    productImage: require("../../assets/horror02.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "horror",
  },{
    _id: uuid(),
    title: "I Travel by Night and Last Train from Perdition",
    author: "Robert McCammon",
    price: "$11.99",
    productImage: require("../../assets/horror03.jpg"),
    inStock: false,
    rating: "4",
    isFastDelivery: false,
    categoryName: "horror",
  },{
    _id: uuid(),
    title: "I Will Find You",
    author: "Amanda Rigby",
    price: "$1.99",
    productImage: require("../../assets/horror04.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: true,
    categoryName: "horror",
  },{
    _id: uuid(),
    title: "Maritime Madness",
    author: "Michael David Sarbone",
    price: "$2.99",
    productImage: require("../../assets/horror05.jpg"),
    inStock: true,
    rating: "5",
    isFastDelivery: false,
    categoryName: "horror",
  },{
    _id: uuid(),
    title: "Beasts of Immortality: Blood and Purpose",
    author: "Paul J Kearns",
    price: "$2.99",
    productImage: require("../../assets/horror06.jpg"),
    inStock: false,
    rating: "4",
    isFastDelivery: false,
    categoryName: "horror",
  },{
    _id: uuid(),
    title: "Dim Shores Presents Volume 2",
    author: "Sam Cowan",
    price: "$3.99",
    productImage: require("../../assets/horror07.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: true,
    categoryName: "horror",
  },{
    _id: uuid(),
    title: "Zoom through Doom",
    author: " Ashok Malli",
    price: "$1.99",
    productImage: require("../../assets/horror08.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "horror",
  },{
    _id: uuid(),
    title: "Before I Sleep",
    author: "L.J. Keys, Luc Bardi",
    price: "$7.00",
    productImage: require("../../assets/horror09.jpg"),
    inStock: false,
    rating: "3",
    isFastDelivery: false,
    categoryName: "horror",
  },{
    _id: uuid(),
    title: "Cursed Legacy",
    author: "D. E. Grant",
    price: "$9.99",
    productImage: require("../../assets/horror10.jpg"),
    inStock: true,
    rating: "5",
    isFastDelivery: false,
    categoryName: "horror",
  },{
    _id: uuid(),
    title: "The King in Yellow (Warbler Classics Annotated Edition)",
    author: "Robert W. Chambers, H. P. Lovecraft",
    price: "$2.99",
    productImage: require("../../assets/horror11.jpg"),
    inStock: false,
    rating: "3",
    isFastDelivery: false,
    categoryName: "horror",
  },{
    _id: uuid(),
    title: "Black House",
    author: " Elana Gomel",
    price: "$3.99",
    productImage: require("../../assets/horror12.jpg"),
    inStock: true,
    rating: "5",
    isFastDelivery: false,
    categoryName: "horror",
  },{
    _id: uuid(),
    title: "Something More Than Night",
    author: "Kim Newman",
    price: "$10.49",
    productImage: require("../../assets/horror13.jpg"),
    inStock: true,
    rating: "5",
    isFastDelivery: false,
    categoryName: "horror",
  },{
    _id: uuid(),
    title: "The Wild Dark",
    author: "Katherine Silva",
    price: "$8.99",
    productImage: require("../../assets/horror14.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "horror",
  },
  {
    _id: uuid(),
    title: "The False Rose",
    author: "Jakob Wegelius, Jakob Wegelius, Peter Graves",
    price: "$12.26",
    productImage: require("../../assets/childteens00.jpg"),
    inStock: true,
    rating: "5",
    isFastDelivery: false,
    categoryName: "children & teens",
  },
  {
    _id: uuid(),
    title: "My Big Heart-Shaped Fail",
    author: "Cindy Callaghan",
    price: "$7.95",
    productImage: require("../../assets/childteens01.jpg"),
    inStock: true,
    rating: "5",
    isFastDelivery: true,
    categoryName: "children & teens",
  },
  {
    _id: uuid(),
    title: "Call Me Penny Pickleberry",
    author: "Meghan Grana, Fanny Liem",
    price: "$9.99",
    productImage: require("../../assets/childteens02.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "children & teens",
  },{
    _id: uuid(),
    title: "I Can Explain",
    author: "Shinsuke Yoshitake",
    price: "$11.99",
    productImage: require("../../assets/childteens03.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "children & teens",
  },{
    _id: uuid(),
    title: "The Impossible Girl",
    author: " Ashley White, Haley Hwang",
    price: "$9.99",
    productImage: require("../../assets/childteens04.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "children & teens",
  },{
    _id: uuid(),
    title: "The Wind Rises",
    author: "Timothée de Fombelle, François Place, Holly James",
    price: "$14.99",
    productImage: require("../../assets/childteens05.jpg"),
    inStock: false,
    rating: "4",
    isFastDelivery: false,
    categoryName: "children & teens",
  },{
    _id: uuid(),
    title: "Fox & Chick: Up and Down",
    author: "Sergio Ruzzier",
    price: "$9.99",
    productImage: require("../../assets/childteens06.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "children & teens",
  },{
    _id: uuid(),
    title: "One Boy Watching",
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    author: " Grant Snider",
    price: "$11.99",
    productImage: require("../../assets/childteens07.jpg"),
    categoryName: "children & teens",
  },{
    _id: uuid(),
    title: "The Lost Ryū",
    author: "Emi Watanabe Cohen",
    price: "$17.99",
    productImage: require("../../assets/childteens08.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: true,
    categoryName: "children & teens",
  },{
    _id: uuid(),
    title: "Love in the Age of Dragons",
    author: " Fatima Henson",
    price: "$9.95",
    productImage: require("../../assets/childteens09.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "children & teens",
  },{
    _id: uuid(),
    title: "Reign Returned",
    author: " Katie Keridan",
    price: "$9.95",
    productImage: require("../../assets/childteens10.jpg"),
    inStock: true,
    rating: "5",
    isFastDelivery: false,
    categoryName: "children & teens",
  },{
    _id: uuid(),
    title: "The Year Without a Summer",
    author: " Arlene Mark",
    price: "$9.95",
    productImage: require("../../assets/childteens11.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "children & teens",
  },{
    _id: uuid(),
    title: "Travelers",
    author: "Brett Riley",
    price: "$9.99",
    productImage: require("../../assets/childteens12.jpg"),
    inStock: false,
    rating: "4",
    isFastDelivery: false,
    categoryName: "children & teens",
  },{
    _id: uuid(),
    title: "A Kiss to Wake Me",
    author: "Cheryl Eager",
    price: "$6.99",
    productImage: require("../../assets/childteens13.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "children & teens",
  },{
    _id: uuid(),
    title: "Ride With Me",
    author: "Lucy Keating",
    price: "$26.99",
    productImage: require("../../assets/childteens14.jpg"),
    inStock: true,
    rating: "5",
    isFastDelivery: false,
    categoryName: "children & teens",
  },
  {
    _id: uuid(),
    title: "You Are Worthy",
    author: "Kelley Holland",
    price: "$9.95",
    productImage: require("../../assets/personalD00.jpg"),
    inStock: false,
    rating: "3",
    isFastDelivery: false,
    categoryName: "personal development",
  },
  {
    _id: uuid(),
    title: "I Wish I’d Known This",
    author: "Brenda Wensil, Kathryn Heath",
    price: "$17.95",
    productImage: require("../../assets/personalD01.jpg"),
    inStock: true,
    rating: "5",
    isFastDelivery: false,
    categoryName: "personal development",
  },{
    _id: uuid(),
    title: "The Power of Your Subconscious Mind A Guide for Teens",
    author: "Dr. Joseph Murphy",
    price: "$14.98",
    productImage: require("../../assets/personalD03.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "personal development",
  },{
    _id: uuid(),
    title: "The Journey Beyond Enlightenment",
    author: "Stuart Wilde",
    price: "$14.98",
    productImage: require("../../assets/personalD04.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "personal development",
  },{
    _id: uuid(),
    title: "It's All in Your Head",
    author: "Suzanne O'Sullivan",
    price: "$594.00",
    productImage: require("../../assets/personalD05.jpg"),
    inStock: true,
    rating: "3",
    isFastDelivery: false,
    categoryName: "personal development",
  },{
    _id: uuid(),
    title: "The Results Mindset",
    author: "Sandy Gallagher, Bob Proctor",
    price: "$14.98",
    productImage: require("../../assets/personalD06.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "personal development",
  },{
    _id: uuid(),
    title: "The Leadership Constant",
    author: "Judy Morley",
    price: "$14.98",
    productImage: require("../../assets/personalD07.jpg"),
    inStock: true,
    rating: "5",
    isFastDelivery: false,
    categoryName: "personal development",
  },{
    _id: uuid(),
    title: "Mother Is a Verb",
    author: "Mina Parker",
    price: "$9.99",
    productImage: require("../../assets/personalD08.jpg"),
    inStock: false,
    rating: "3",
    isFastDelivery: false,
    categoryName: "personal development",
  },{
    _id: uuid(),
    title: "Away Up the North Fork",
    author: "Annie Chappell",
    price: "$9.95",
    productImage: require("../../assets/personalD09.jpg"),
    inStock: true,
    rating: "5",
    isFastDelivery: false,
    categoryName: "personal development",
  },{
    _id: uuid(),
    title: "Regifted",
    author: "Candi Byrne",
    price: "$9.95",
    productImage: require("../../assets/personalD10.jpg"),
    inStock: true,
    rating: "5",
    isFastDelivery: true,
    categoryName: "personal development",
  },{
    _id: uuid(),
    title: "Jane's Jam",
    author: "Jane Enright", 
    productImage: require("../../assets/personalD11.jpg"),
    inStock: false,
    rating: "4",
    isFastDelivery: false,
    categoryName: "personal development",
  },{
    _id: uuid(),
    title: "Get Rich Now",
    author: "Brian Tracy",
    price: "$14.98",
    productImage: require("../../assets/personalD12.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "personal development",
  },{
    _id: uuid(),
    title: "The 7 Secret Treasures",
    author: "John Demartini",
    price: "$14.98",
    productImage: require("../../assets/personalD13.jpg"),
    inStock: true,
    rating: "5",
    isFastDelivery: false,
    categoryName: "personal development",
  },{
    _id: uuid(),
    title: "More Than You Can See",
    author: "Barbara Rubin",
    price: "$9.95",
    productImage: require("../../assets/personalD14.jpg"),
    inStock: false,
    rating: "4",
    isFastDelivery: false,
    categoryName: "personal development",
  },{
    _id: uuid(),
    title: "You Are Worthy",
    author: "Kelley Holland",
    price: "$9.95",
    productImage: require("../../assets/personalD15.jpg"),
    inStock: false,
    rating: "5",
    isFastDelivery: false,
    categoryName: "personal development",
  },
  
];
